server:
  port: 5000

sdot:
  url: "https://web6.seattle.gov/Travelers/api/Map/GetBridgeData"

aws:
  secrets:
    bucket: brdges-data-service

cache:
  bridges:
    refresh:
      intervalMillis: 60000

app:
  version: ssl-1.1